# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d7827de55808612cb3e29f7c150a05bb2b6507e101c619c09d3985bf406f615931de48d858e621d537b4009c6fe8801ed99ed2d6379016599fb5e246f23ece

test:
  secret_key_base: 6e707cf8d47a43b0cd164aee048df7a6832d8dbb712979159af3deb4dded72173c4d62ac8fb25e785ebae92325a6fb86bf63b9eba189e9cc0b80589235a4cfac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
